/**
 * Generates type-safe contract wrappers for protocol contracts.
 * These wrappers use a minimal artifact (without bytecode) since PXE already has the full artifacts registered.
 */
import {
  type ABIParameter,
  type ContractArtifact,
  type FunctionAbi,
  FunctionType,
  getAllFunctionAbis,
  isAztecAddressStruct,
  isBoundedVecStruct,
  isEthAddressStruct,
  isFunctionSelectorStruct,
  isWrappedFieldStruct,
  loadContractArtifact,
} from '@aztec/stdlib/abi';
import type { NoirCompiledContract } from '@aztec/stdlib/noir';

import { promises as fs } from 'fs';
import path from 'path';

const log = console.log;

const noirContractsRoot = path.join(import.meta.dirname, '../../../../noir-projects/noir-contracts');
const srcPath = path.join(noirContractsRoot, 'target');
const outputDir = path.join(import.meta.dirname, '../contract/protocol_contracts');

function toKebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function abiTypeToTypescript(type: ABIParameter['type']): string {
  switch (type.kind) {
    case 'field':
      return 'FieldLike';
    case 'boolean':
      return 'boolean';
    case 'integer':
      return '(bigint | number)';
    case 'string':
      return 'string';
    case 'array':
      return `${abiTypeToTypescript(type.type)}[]`;
    case 'struct':
      if (isEthAddressStruct(type)) {
        return 'EthAddressLike';
      }
      if (isAztecAddressStruct(type)) {
        return 'AztecAddressLike';
      }
      if (isFunctionSelectorStruct(type)) {
        return 'FunctionSelectorLike';
      }
      if (isWrappedFieldStruct(type)) {
        return 'WrappedFieldLike';
      }
      if (isBoundedVecStruct(type)) {
        return `${abiTypeToTypescript(type.fields[0].type)}`;
      }
      // Complex structs use 'any' because the encoder accepts objects with encodeToNoir() method
      return 'any';
    default:
      throw new Error(`Unknown type ${type.kind}`);
  }
}

function generateMethod(entry: FunctionAbi) {
  const args = entry.parameters.map(p => `${p.name}: ${abiTypeToTypescript(p.type)}`).join(', ');
  return `
    /** ${entry.name}(${entry.parameters.map(p => `${p.name}: ${p.type.kind}`).join(', ')}) */
    ${entry.name}: ((${args}) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;`;
}

function functionTypeToEnum(type: FunctionType): string {
  switch (type) {
    case FunctionType.PRIVATE:
      return 'FunctionType.PRIVATE';
    case FunctionType.PUBLIC:
      return 'FunctionType.PUBLIC';
    case FunctionType.UTILITY:
      return 'FunctionType.UTILITY';
  }
}

function generateFunctionAbiJson(abi: FunctionAbi): string {
  const baseObj = {
    name: abi.name,
    isOnlySelf: abi.isOnlySelf,
    isStatic: abi.isStatic,
    isInitializer: abi.isInitializer,
    parameters: abi.parameters,
    returnTypes: abi.returnTypes,
    errorTypes: abi.errorTypes,
  };
  const jsonStr = JSON.stringify(baseObj);
  // Insert functionType as an enum reference (not a string)
  return jsonStr.replace('{', `{ functionType: ${functionTypeToEnum(abi.functionType)},`);
}

function generateProtocolContractArtifact(input: ContractArtifact): string {
  const allAbis = getAllFunctionAbis(input);
  const functionAbis = input.functions.map(f => allAbis.find(abi => abi.name === f.name)!);
  const nonDispatchAbis = input.nonDispatchPublicFunctions;

  const functionsArray = functionAbis
    .map(abi => `{ ...${generateFunctionAbiJson(abi)}, bytecode: Buffer.from([]), debugSymbols: '' }`)
    .join(',\n    ');

  const nonDispatchArray = nonDispatchAbis.map(abi => generateFunctionAbiJson(abi)).join(',\n    ');

  return `{
  name: '${input.name}',
  functions: [
    ${functionsArray}
  ],
  nonDispatchPublicFunctions: [
    ${nonDispatchArray}
  ],
  outputs: { structs: {}, globals: {} },
  storageLayout: {},
  fileMap: {},
}`;
}

function generateProtocolContractInterface(input: ContractArtifact, protocolContractName: string): string {
  const methods = getAllFunctionAbis(input)
    .filter(f => !f.isOnlySelf)
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(generateMethod);

  const artifactCode = generateProtocolContractArtifact(input);
  const contractName = `${input.name}Contract`;

  return `
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { ProtocolContractAddress } from '@aztec/protocol-contracts';
import { FunctionType } from '@aztec/stdlib/abi';

import type { ContractArtifact } from '../../api/abi.js';
import type { AztecAddressLike, EthAddressLike, FieldLike, FunctionSelectorLike, WrappedFieldLike } from '../../utils/abi_types.js';
import { ContractBase, type ContractMethod } from '../contract_base.js';
import { ContractFunctionInteraction } from '../contract_function_interaction.js';
import type { Wallet } from '../../wallet/wallet.js';

const ${contractName}Artifact: ContractArtifact = ${artifactCode};

export class ${contractName} extends ContractBase {
  private constructor(wallet: Wallet) {
    super(ProtocolContractAddress.${protocolContractName}, ${contractName}Artifact, wallet);
  }

  public static at(wallet: Wallet): ${contractName} {
    return new ${contractName}(wallet);
  }

  public declare methods: {
    ${methods.join('\n')}
  };
}
`;
}

async function main() {
  await fs.rm(outputDir, { recursive: true, force: true });
  await fs.mkdir(outputDir, { recursive: true });

  // Read the list of protocol contracts from noir-projects (same source as protocol-contracts package)
  const srcNames = JSON.parse(
    await fs.readFile(path.join(noirContractsRoot, 'protocol_contracts.json'), 'utf8'),
  ) as string[];

  for (const srcName of srcNames) {
    // srcName is like "auth_registry_contract-AuthRegistry", split to get the contract name
    const name = srcName.split('-')[1];
    const artifactPath = path.join(srcPath, `${srcName}.json`);
    const json = JSON.parse(await fs.readFile(artifactPath, 'utf8')) as NoirCompiledContract;
    const contractArtifact = loadContractArtifact(json);

    const content = generateProtocolContractInterface(contractArtifact, name);
    const fileName = `${toKebabCase(name)}.ts`;
    await fs.writeFile(path.join(outputDir, fileName), content);

    log(`Generated ${fileName}`);
  }
}

main().catch(err => {
  console.error('Error generating protocol contract types:', err);
  process.exit(1);
});
