/* Autogenerated file, do not edit! */
/* eslint-disable */
import { ProtocolContractAddress } from '@aztec/protocol-contracts';
import { FunctionType } from '@aztec/stdlib/abi';

import type { ContractArtifact } from '../../api/abi.js';
import type {
  AztecAddressLike,
  EthAddressLike,
  FieldLike,
  FunctionSelectorLike,
  WrappedFieldLike,
} from '../../utils/abi_types.js';
import type { Wallet } from '../../wallet/wallet.js';
import { ContractBase, type ContractMethod } from '../contract_base.js';
import { ContractFunctionInteraction } from '../contract_function_interaction.js';

const AuthRegistryContractArtifact: ContractArtifact = {
  name: 'AuthRegistry',
  functions: [
    {
      ...{
        functionType: FunctionType.PRIVATE,
        name: 'set_authorized_private',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [
          {
            name: 'approver',
            type: {
              kind: 'struct',
              fields: [{ name: 'inner', type: { kind: 'field' } }],
              path: 'aztec::protocol_types::address::aztec_address::AztecAddress',
            },
            visibility: 'private',
          },
          { name: 'message_hash', type: { kind: 'field' }, visibility: 'private' },
          { name: 'authorize', type: { kind: 'boolean' }, visibility: 'private' },
        ],
        returnTypes: [],
        errorTypes: {
          '2754040237334517471': { error_kind: 'fmtstring', length: 92, item_types: [] },
          '7555607922535724711': { error_kind: 'string', string: 'Preimage mismatch' },
          '9894212961085021188': { error_kind: 'string', string: 'Message not authorized by account' },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.UTILITY,
        name: 'utility_is_consumable',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [
          {
            name: 'on_behalf_of',
            type: {
              kind: 'struct',
              fields: [{ name: 'inner', type: { kind: 'field' } }],
              path: 'aztec::protocol_types::address::aztec_address::AztecAddress',
            },
            visibility: 'private',
          },
          { name: 'message_hash', type: { kind: 'field' }, visibility: 'private' },
        ],
        returnTypes: [{ kind: 'boolean' }],
        errorTypes: {
          '13455385521185560676': {
            error_kind: 'string',
            string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.UTILITY,
        name: 'process_message',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [
          {
            name: 'message_ciphertext',
            type: {
              kind: 'struct',
              fields: [
                { name: 'storage', type: { kind: 'array', length: 17, type: { kind: 'field' } } },
                { name: 'len', type: { kind: 'integer', sign: 'unsigned', width: 32 } },
              ],
              path: 'std::collections::bounded_vec::BoundedVec',
            },
            visibility: 'private',
          },
          {
            name: 'message_context',
            type: {
              kind: 'struct',
              fields: [
                { name: 'tx_hash', type: { kind: 'field' } },
                {
                  name: 'unique_note_hashes_in_tx',
                  type: {
                    kind: 'struct',
                    fields: [
                      { name: 'storage', type: { kind: 'array', length: 64, type: { kind: 'field' } } },
                      { name: 'len', type: { kind: 'integer', sign: 'unsigned', width: 32 } },
                    ],
                    path: 'std::collections::bounded_vec::BoundedVec',
                  },
                },
                { name: 'first_nullifier_in_tx', type: { kind: 'field' } },
                {
                  name: 'recipient',
                  type: {
                    kind: 'struct',
                    fields: [{ name: 'inner', type: { kind: 'field' } }],
                    path: 'aztec::protocol_types::address::aztec_address::AztecAddress',
                  },
                },
              ],
              path: 'aztec::messages::processing::message_context::MessageContext',
            },
            visibility: 'private',
          },
        ],
        returnTypes: [],
        errorTypes: {
          '361444214588792908': { error_kind: 'string', string: 'attempt to multiply with overflow' },
          '992401946138144806': { error_kind: 'string', string: 'Attempted to read past end of BoundedVec' },
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '2967937905572420042': {
            error_kind: 'fmtstring',
            length: 61,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3330370348214585450': {
            error_kind: 'fmtstring',
            length: 48,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3670003311596808700': {
            error_kind: 'fmtstring',
            length: 77,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '4261968856572588300': { error_kind: 'string', string: 'Value does not fit in field' },
          '4440399188109668273': { error_kind: 'string', string: 'Input length must be a multiple of 32' },
          '9791669845391776238': {
            error_kind: 'string',
            string: '0 has a square root; you cannot claim it is not square',
          },
          '9885968605480832328': {
            error_kind: 'string',
            string: 'Attempted to read past the length of a CapsuleArray',
          },
          '10135509984888824963': { error_kind: 'fmtstring', length: 58, item_types: [{ kind: 'field' }] },
          '10791800398362570014': { error_kind: 'string', string: 'extend_from_bounded_vec out of bounds' },
          '11021520179822076911': {
            error_kind: 'string',
            string: 'Attempted to delete past the length of a CapsuleArray',
          },
          '11692359521570349358': { error_kind: 'fmtstring', length: 40, item_types: [] },
          '12327971061804302172': { error_kind: 'fmtstring', length: 98, item_types: [] },
          '12469291177396340830': { error_kind: 'string', string: 'call to assert_max_bit_size' },
          '12913276134398371456': { error_kind: 'string', string: 'push out of bounds' },
          '13557316507370296400': {
            error_kind: 'fmtstring',
            length: 130,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14938672389828944159': {
            error_kind: 'fmtstring',
            length: 146,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
          '17531474008201752295': {
            error_kind: 'fmtstring',
            length: 133,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.PUBLIC,
        name: 'public_dispatch',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [{ name: 'selector', type: { kind: 'field' }, visibility: 'private' }],
        returnTypes: [],
        errorTypes: {
          '5525725861591553972': { error_kind: 'string', string: 'rejecting all' },
          '11691217184967371519': {
            error_kind: 'string',
            string: 'Function is_reject_all can only be called statically',
          },
          '12511970388699677811': { error_kind: 'fmtstring', length: 27, item_types: [{ kind: 'field' }] },
          '13455385521185560676': {
            error_kind: 'string',
            string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
          },
          '13929691561421487185': {
            error_kind: 'string',
            string: 'Function _set_authorized can only be called by the same contract',
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
          '17089945683942782951': { error_kind: 'string', string: 'unauthorized' },
          '17312933876399746100': {
            error_kind: 'string',
            string: 'Function is_consumable can only be called statically',
          },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.UTILITY,
        name: 'sync_private_state',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [],
        returnTypes: [],
        errorTypes: {
          '361444214588792908': { error_kind: 'string', string: 'attempt to multiply with overflow' },
          '992401946138144806': { error_kind: 'string', string: 'Attempted to read past end of BoundedVec' },
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '2967937905572420042': {
            error_kind: 'fmtstring',
            length: 61,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3330370348214585450': {
            error_kind: 'fmtstring',
            length: 48,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3670003311596808700': {
            error_kind: 'fmtstring',
            length: 77,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '4261968856572588300': { error_kind: 'string', string: 'Value does not fit in field' },
          '4440399188109668273': { error_kind: 'string', string: 'Input length must be a multiple of 32' },
          '9791669845391776238': {
            error_kind: 'string',
            string: '0 has a square root; you cannot claim it is not square',
          },
          '9885968605480832328': {
            error_kind: 'string',
            string: 'Attempted to read past the length of a CapsuleArray',
          },
          '10135509984888824963': { error_kind: 'fmtstring', length: 58, item_types: [{ kind: 'field' }] },
          '10791800398362570014': { error_kind: 'string', string: 'extend_from_bounded_vec out of bounds' },
          '11021520179822076911': {
            error_kind: 'string',
            string: 'Attempted to delete past the length of a CapsuleArray',
          },
          '11692359521570349358': { error_kind: 'fmtstring', length: 40, item_types: [] },
          '12327971061804302172': { error_kind: 'fmtstring', length: 98, item_types: [] },
          '12469291177396340830': { error_kind: 'string', string: 'call to assert_max_bit_size' },
          '12913276134398371456': { error_kind: 'string', string: 'push out of bounds' },
          '13557316507370296400': {
            error_kind: 'fmtstring',
            length: 130,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14938672389828944159': {
            error_kind: 'fmtstring',
            length: 146,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
          '17531474008201752295': {
            error_kind: 'fmtstring',
            length: 133,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
  ],
  nonDispatchPublicFunctions: [
    {
      functionType: FunctionType.PUBLIC,
      name: '_set_authorized',
      isOnlySelf: true,
      isStatic: false,
      isInitializer: false,
      parameters: [
        {
          name: 'approver',
          type: {
            kind: 'struct',
            fields: [{ name: 'inner', type: { kind: 'field' } }],
            path: 'aztec::protocol_types::address::aztec_address::AztecAddress',
          },
          visibility: 'private',
        },
        { name: 'message_hash', type: { kind: 'field' }, visibility: 'private' },
        { name: 'authorize', type: { kind: 'boolean' }, visibility: 'private' },
      ],
      returnTypes: [],
      errorTypes: {
        '13455385521185560676': {
          error_kind: 'string',
          string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
        },
        '13929691561421487185': {
          error_kind: 'string',
          string: 'Function _set_authorized can only be called by the same contract',
        },
        '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
        '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
        '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
      },
    },
    {
      functionType: FunctionType.PUBLIC,
      name: 'consume',
      isOnlySelf: false,
      isStatic: false,
      isInitializer: false,
      parameters: [
        {
          name: 'on_behalf_of',
          type: {
            kind: 'struct',
            fields: [{ name: 'inner', type: { kind: 'field' } }],
            path: 'aztec::protocol_types::address::aztec_address::AztecAddress',
          },
          visibility: 'private',
        },
        { name: 'inner_hash', type: { kind: 'field' }, visibility: 'private' },
      ],
      returnTypes: [{ kind: 'field' }],
      errorTypes: {
        '5525725861591553972': { error_kind: 'string', string: 'rejecting all' },
        '13455385521185560676': {
          error_kind: 'string',
          string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
        },
        '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
        '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
        '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
        '17089945683942782951': { error_kind: 'string', string: 'unauthorized' },
      },
    },
    {
      functionType: FunctionType.PUBLIC,
      name: 'is_consumable',
      isOnlySelf: false,
      isStatic: true,
      isInitializer: false,
      parameters: [
        {
          name: 'on_behalf_of',
          type: {
            kind: 'struct',
            fields: [{ name: 'inner', type: { kind: 'field' } }],
            path: 'aztec::protocol_types::address::aztec_address::AztecAddress',
          },
          visibility: 'private',
        },
        { name: 'message_hash', type: { kind: 'field' }, visibility: 'private' },
      ],
      returnTypes: [{ kind: 'boolean' }],
      errorTypes: {
        '13455385521185560676': {
          error_kind: 'string',
          string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
        },
        '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
        '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
        '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
        '17312933876399746100': {
          error_kind: 'string',
          string: 'Function is_consumable can only be called statically',
        },
      },
    },
    {
      functionType: FunctionType.PUBLIC,
      name: 'is_reject_all',
      isOnlySelf: false,
      isStatic: true,
      isInitializer: false,
      parameters: [
        {
          name: 'on_behalf_of',
          type: {
            kind: 'struct',
            fields: [{ name: 'inner', type: { kind: 'field' } }],
            path: 'aztec::protocol_types::address::aztec_address::AztecAddress',
          },
          visibility: 'private',
        },
      ],
      returnTypes: [{ kind: 'boolean' }],
      errorTypes: {
        '11691217184967371519': {
          error_kind: 'string',
          string: 'Function is_reject_all can only be called statically',
        },
        '13455385521185560676': {
          error_kind: 'string',
          string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
        },
        '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
      },
    },
    {
      functionType: FunctionType.PUBLIC,
      name: 'set_authorized',
      isOnlySelf: false,
      isStatic: false,
      isInitializer: false,
      parameters: [
        { name: 'message_hash', type: { kind: 'field' }, visibility: 'private' },
        { name: 'authorize', type: { kind: 'boolean' }, visibility: 'private' },
      ],
      returnTypes: [],
      errorTypes: {
        '13455385521185560676': {
          error_kind: 'string',
          string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
        },
        '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
        '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
        '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
      },
    },
    {
      functionType: FunctionType.PUBLIC,
      name: 'set_reject_all',
      isOnlySelf: false,
      isStatic: false,
      isInitializer: false,
      parameters: [{ name: 'reject', type: { kind: 'boolean' }, visibility: 'private' }],
      returnTypes: [],
      errorTypes: {
        '13455385521185560676': {
          error_kind: 'string',
          string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
        },
        '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
      },
    },
  ],
  outputs: { structs: {}, globals: {} },
  storageLayout: {},
  fileMap: {},
};

export class AuthRegistryContract extends ContractBase {
  private constructor(wallet: Wallet) {
    super(ProtocolContractAddress.AuthRegistry, AuthRegistryContractArtifact, wallet);
  }

  public static at(wallet: Wallet): AuthRegistryContract {
    return new AuthRegistryContract(wallet);
  }

  declare public methods: {
    /** consume(on_behalf_of: struct, inner_hash: field) */
    consume: ((on_behalf_of: AztecAddressLike, inner_hash: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** is_consumable(on_behalf_of: struct, message_hash: field) */
    is_consumable: ((on_behalf_of: AztecAddressLike, message_hash: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** is_reject_all(on_behalf_of: struct) */
    is_reject_all: ((on_behalf_of: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: any) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_authorized(message_hash: field, authorize: boolean) */
    set_authorized: ((message_hash: FieldLike, authorize: boolean) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** set_authorized_private(approver: struct, message_hash: field, authorize: boolean) */
    set_authorized_private: ((
      approver: AztecAddressLike,
      message_hash: FieldLike,
      authorize: boolean,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** set_reject_all(reject: boolean) */
    set_reject_all: ((reject: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** utility_is_consumable(on_behalf_of: struct, message_hash: field) */
    utility_is_consumable: ((on_behalf_of: AztecAddressLike, message_hash: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;
  };
}
