/* Autogenerated file, do not edit! */
/* eslint-disable */
import { ProtocolContractAddress } from '@aztec/protocol-contracts';
import { FunctionType } from '@aztec/stdlib/abi';

import type { ContractArtifact } from '../../api/abi.js';
import type {
  AztecAddressLike,
  EthAddressLike,
  FieldLike,
  FunctionSelectorLike,
  WrappedFieldLike,
} from '../../utils/abi_types.js';
import type { Wallet } from '../../wallet/wallet.js';
import { ContractBase, type ContractMethod } from '../contract_base.js';
import { ContractFunctionInteraction } from '../contract_function_interaction.js';

const ContractInstanceRegistryContractArtifact: ContractArtifact = {
  name: 'ContractInstanceRegistry',
  functions: [
    {
      ...{
        functionType: FunctionType.PRIVATE,
        name: 'publish_for_public_execution',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [
          { name: 'salt', type: { kind: 'field' }, visibility: 'private' },
          {
            name: 'contract_class_id',
            type: {
              kind: 'struct',
              fields: [{ name: 'inner', type: { kind: 'field' } }],
              path: 'aztec::protocol_types::contract_class_id::ContractClassId',
            },
            visibility: 'private',
          },
          { name: 'initialization_hash', type: { kind: 'field' }, visibility: 'private' },
          {
            name: 'public_keys',
            type: {
              kind: 'struct',
              fields: [
                {
                  name: 'npk_m',
                  type: {
                    kind: 'struct',
                    fields: [
                      {
                        name: 'inner',
                        type: {
                          kind: 'struct',
                          fields: [
                            { name: 'x', type: { kind: 'field' } },
                            { name: 'y', type: { kind: 'field' } },
                            { name: 'is_infinite', type: { kind: 'boolean' } },
                          ],
                          path: 'std::embedded_curve_ops::EmbeddedCurvePoint',
                        },
                      },
                    ],
                    path: 'aztec::protocol_types::public_keys::NpkM',
                  },
                },
                {
                  name: 'ivpk_m',
                  type: {
                    kind: 'struct',
                    fields: [
                      {
                        name: 'inner',
                        type: {
                          kind: 'struct',
                          fields: [
                            { name: 'x', type: { kind: 'field' } },
                            { name: 'y', type: { kind: 'field' } },
                            { name: 'is_infinite', type: { kind: 'boolean' } },
                          ],
                          path: 'std::embedded_curve_ops::EmbeddedCurvePoint',
                        },
                      },
                    ],
                    path: 'aztec::protocol_types::public_keys::IvpkM',
                  },
                },
                {
                  name: 'ovpk_m',
                  type: {
                    kind: 'struct',
                    fields: [
                      {
                        name: 'inner',
                        type: {
                          kind: 'struct',
                          fields: [
                            { name: 'x', type: { kind: 'field' } },
                            { name: 'y', type: { kind: 'field' } },
                            { name: 'is_infinite', type: { kind: 'boolean' } },
                          ],
                          path: 'std::embedded_curve_ops::EmbeddedCurvePoint',
                        },
                      },
                    ],
                    path: 'aztec::protocol_types::public_keys::OvpkM',
                  },
                },
                {
                  name: 'tpk_m',
                  type: {
                    kind: 'struct',
                    fields: [
                      {
                        name: 'inner',
                        type: {
                          kind: 'struct',
                          fields: [
                            { name: 'x', type: { kind: 'field' } },
                            { name: 'y', type: { kind: 'field' } },
                            { name: 'is_infinite', type: { kind: 'boolean' } },
                          ],
                          path: 'std::embedded_curve_ops::EmbeddedCurvePoint',
                        },
                      },
                    ],
                    path: 'aztec::protocol_types::public_keys::TpkM',
                  },
                },
              ],
              path: 'aztec::protocol_types::public_keys::PublicKeys',
            },
            visibility: 'private',
          },
          { name: 'universal_deploy', type: { kind: 'boolean' }, visibility: 'private' },
        ],
        returnTypes: [],
        errorTypes: {
          '2754040237334517471': { error_kind: 'fmtstring', length: 92, item_types: [] },
          '12469291177396340830': { error_kind: 'string', string: 'call to assert_max_bit_size' },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.UTILITY,
        name: 'process_message',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [
          {
            name: 'message_ciphertext',
            type: {
              kind: 'struct',
              fields: [
                { name: 'storage', type: { kind: 'array', length: 17, type: { kind: 'field' } } },
                { name: 'len', type: { kind: 'integer', sign: 'unsigned', width: 32 } },
              ],
              path: 'std::collections::bounded_vec::BoundedVec',
            },
            visibility: 'private',
          },
          {
            name: 'message_context',
            type: {
              kind: 'struct',
              fields: [
                { name: 'tx_hash', type: { kind: 'field' } },
                {
                  name: 'unique_note_hashes_in_tx',
                  type: {
                    kind: 'struct',
                    fields: [
                      { name: 'storage', type: { kind: 'array', length: 64, type: { kind: 'field' } } },
                      { name: 'len', type: { kind: 'integer', sign: 'unsigned', width: 32 } },
                    ],
                    path: 'std::collections::bounded_vec::BoundedVec',
                  },
                },
                { name: 'first_nullifier_in_tx', type: { kind: 'field' } },
                {
                  name: 'recipient',
                  type: {
                    kind: 'struct',
                    fields: [{ name: 'inner', type: { kind: 'field' } }],
                    path: 'aztec::protocol_types::address::aztec_address::AztecAddress',
                  },
                },
              ],
              path: 'aztec::messages::processing::message_context::MessageContext',
            },
            visibility: 'private',
          },
        ],
        returnTypes: [],
        errorTypes: {
          '361444214588792908': { error_kind: 'string', string: 'attempt to multiply with overflow' },
          '992401946138144806': { error_kind: 'string', string: 'Attempted to read past end of BoundedVec' },
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '2967937905572420042': {
            error_kind: 'fmtstring',
            length: 61,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3330370348214585450': {
            error_kind: 'fmtstring',
            length: 48,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3670003311596808700': {
            error_kind: 'fmtstring',
            length: 77,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '4261968856572588300': { error_kind: 'string', string: 'Value does not fit in field' },
          '4440399188109668273': { error_kind: 'string', string: 'Input length must be a multiple of 32' },
          '9791669845391776238': {
            error_kind: 'string',
            string: '0 has a square root; you cannot claim it is not square',
          },
          '9885968605480832328': {
            error_kind: 'string',
            string: 'Attempted to read past the length of a CapsuleArray',
          },
          '10135509984888824963': { error_kind: 'fmtstring', length: 58, item_types: [{ kind: 'field' }] },
          '10791800398362570014': { error_kind: 'string', string: 'extend_from_bounded_vec out of bounds' },
          '11021520179822076911': {
            error_kind: 'string',
            string: 'Attempted to delete past the length of a CapsuleArray',
          },
          '11692359521570349358': { error_kind: 'fmtstring', length: 40, item_types: [] },
          '12327971061804302172': { error_kind: 'fmtstring', length: 98, item_types: [] },
          '12469291177396340830': { error_kind: 'string', string: 'call to assert_max_bit_size' },
          '12913276134398371456': { error_kind: 'string', string: 'push out of bounds' },
          '13557316507370296400': {
            error_kind: 'fmtstring',
            length: 130,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14938672389828944159': {
            error_kind: 'fmtstring',
            length: 146,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
          '17531474008201752295': {
            error_kind: 'fmtstring',
            length: 133,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.PUBLIC,
        name: 'public_dispatch',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [{ name: 'selector', type: { kind: 'field' }, visibility: 'private' }],
        returnTypes: [],
        errorTypes: {
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '5755400808989454547': {
            error_kind: 'string',
            string: 'Function get_update_delay can only be called statically',
          },
          '6804164082532189961': { error_kind: 'string', string: 'New update delay is too low' },
          '12511970388699677811': { error_kind: 'fmtstring', length: 27, item_types: [{ kind: 'field' }] },
          '12579274401768182412': { error_kind: 'string', string: 'New contract class is not registered' },
          '13455385521185560676': {
            error_kind: 'string',
            string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15353471697975175405': { error_kind: 'string', string: 'msg.sender is not deployed' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.UTILITY,
        name: 'sync_private_state',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [],
        returnTypes: [],
        errorTypes: {
          '361444214588792908': { error_kind: 'string', string: 'attempt to multiply with overflow' },
          '992401946138144806': { error_kind: 'string', string: 'Attempted to read past end of BoundedVec' },
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '2967937905572420042': {
            error_kind: 'fmtstring',
            length: 61,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3330370348214585450': {
            error_kind: 'fmtstring',
            length: 48,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3670003311596808700': {
            error_kind: 'fmtstring',
            length: 77,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '4261968856572588300': { error_kind: 'string', string: 'Value does not fit in field' },
          '4440399188109668273': { error_kind: 'string', string: 'Input length must be a multiple of 32' },
          '9791669845391776238': {
            error_kind: 'string',
            string: '0 has a square root; you cannot claim it is not square',
          },
          '9885968605480832328': {
            error_kind: 'string',
            string: 'Attempted to read past the length of a CapsuleArray',
          },
          '10135509984888824963': { error_kind: 'fmtstring', length: 58, item_types: [{ kind: 'field' }] },
          '10791800398362570014': { error_kind: 'string', string: 'extend_from_bounded_vec out of bounds' },
          '11021520179822076911': {
            error_kind: 'string',
            string: 'Attempted to delete past the length of a CapsuleArray',
          },
          '11692359521570349358': { error_kind: 'fmtstring', length: 40, item_types: [] },
          '12327971061804302172': { error_kind: 'fmtstring', length: 98, item_types: [] },
          '12469291177396340830': { error_kind: 'string', string: 'call to assert_max_bit_size' },
          '12913276134398371456': { error_kind: 'string', string: 'push out of bounds' },
          '13557316507370296400': {
            error_kind: 'fmtstring',
            length: 130,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14938672389828944159': {
            error_kind: 'fmtstring',
            length: 146,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
          '17531474008201752295': {
            error_kind: 'fmtstring',
            length: 133,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
  ],
  nonDispatchPublicFunctions: [
    {
      functionType: FunctionType.PUBLIC,
      name: 'get_update_delay',
      isOnlySelf: false,
      isStatic: true,
      isInitializer: false,
      parameters: [],
      returnTypes: [{ kind: 'integer', sign: 'unsigned', width: 64 }],
      errorTypes: {
        '5755400808989454547': {
          error_kind: 'string',
          string: 'Function get_update_delay can only be called statically',
        },
        '13455385521185560676': {
          error_kind: 'string',
          string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
        },
        '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
      },
    },
    {
      functionType: FunctionType.PUBLIC,
      name: 'set_update_delay',
      isOnlySelf: false,
      isStatic: false,
      isInitializer: false,
      parameters: [
        { name: 'new_update_delay', type: { kind: 'integer', sign: 'unsigned', width: 64 }, visibility: 'private' },
      ],
      returnTypes: [],
      errorTypes: {
        '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
        '6804164082532189961': { error_kind: 'string', string: 'New update delay is too low' },
        '13455385521185560676': {
          error_kind: 'string',
          string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
        },
        '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
        '15353471697975175405': { error_kind: 'string', string: 'msg.sender is not deployed' },
        '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
        '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
      },
    },
    {
      functionType: FunctionType.PUBLIC,
      name: 'update',
      isOnlySelf: false,
      isStatic: false,
      isInitializer: false,
      parameters: [
        {
          name: 'new_contract_class_id',
          type: {
            kind: 'struct',
            fields: [{ name: 'inner', type: { kind: 'field' } }],
            path: 'aztec::protocol_types::contract_class_id::ContractClassId',
          },
          visibility: 'private',
        },
      ],
      returnTypes: [],
      errorTypes: {
        '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
        '12579274401768182412': { error_kind: 'string', string: 'New contract class is not registered' },
        '13455385521185560676': {
          error_kind: 'string',
          string: 'Storage slot 0 not allowed. Storage slots must start from 1.',
        },
        '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
        '15353471697975175405': { error_kind: 'string', string: 'msg.sender is not deployed' },
        '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
        '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
      },
    },
  ],
  outputs: { structs: {}, globals: {} },
  storageLayout: {},
  fileMap: {},
};

export class ContractInstanceRegistryContract extends ContractBase {
  private constructor(wallet: Wallet) {
    super(ProtocolContractAddress.ContractInstanceRegistry, ContractInstanceRegistryContractArtifact, wallet);
  }

  public static at(wallet: Wallet): ContractInstanceRegistryContract {
    return new ContractInstanceRegistryContract(wallet);
  }

  declare public methods: {
    /** get_update_delay() */
    get_update_delay: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: any) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** publish_for_public_execution(salt: field, contract_class_id: struct, initialization_hash: field, public_keys: struct, universal_deploy: boolean) */
    publish_for_public_execution: ((
      salt: FieldLike,
      contract_class_id: WrappedFieldLike,
      initialization_hash: FieldLike,
      public_keys: any,
      universal_deploy: boolean,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** set_update_delay(new_update_delay: integer) */
    set_update_delay: ((new_update_delay: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update(new_contract_class_id: struct) */
    update: ((new_contract_class_id: WrappedFieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;
  };
}
