/* Autogenerated file, do not edit! */
/* eslint-disable */
import { ProtocolContractAddress } from '@aztec/protocol-contracts';
import { FunctionType } from '@aztec/stdlib/abi';

import type { ContractArtifact } from '../../api/abi.js';
import type {
  AztecAddressLike,
  EthAddressLike,
  FieldLike,
  FunctionSelectorLike,
  WrappedFieldLike,
} from '../../utils/abi_types.js';
import type { Wallet } from '../../wallet/wallet.js';
import { ContractBase, type ContractMethod } from '../contract_base.js';
import { ContractFunctionInteraction } from '../contract_function_interaction.js';

const ContractClassRegistryContractArtifact: ContractArtifact = {
  name: 'ContractClassRegistry',
  functions: [
    {
      ...{
        functionType: FunctionType.PRIVATE,
        name: 'broadcast_private_function',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [
          {
            name: 'contract_class_id',
            type: {
              kind: 'struct',
              fields: [{ name: 'inner', type: { kind: 'field' } }],
              path: 'aztec::protocol_types::contract_class_id::ContractClassId',
            },
            visibility: 'private',
          },
          { name: 'artifact_metadata_hash', type: { kind: 'field' }, visibility: 'private' },
          { name: 'utility_functions_artifact_tree_root', type: { kind: 'field' }, visibility: 'private' },
          {
            name: 'private_function_tree_sibling_path',
            type: { kind: 'array', length: 7, type: { kind: 'field' } },
            visibility: 'private',
          },
          { name: 'private_function_tree_leaf_index', type: { kind: 'field' }, visibility: 'private' },
          {
            name: 'artifact_function_tree_sibling_path',
            type: { kind: 'array', length: 7, type: { kind: 'field' } },
            visibility: 'private',
          },
          { name: 'artifact_function_tree_leaf_index', type: { kind: 'field' }, visibility: 'private' },
          {
            name: 'function_data',
            type: {
              kind: 'struct',
              fields: [
                {
                  name: 'selector',
                  type: {
                    kind: 'struct',
                    fields: [{ name: 'inner', type: { kind: 'integer', sign: 'unsigned', width: 32 } }],
                    path: 'aztec::protocol_types::abis::function_selector::FunctionSelector',
                  },
                },
                { name: 'metadata_hash', type: { kind: 'field' } },
                { name: 'vk_hash', type: { kind: 'field' } },
              ],
              path: 'events::private_function_broadcasted::InnerPrivateFunction',
            },
            visibility: 'private',
          },
        ],
        returnTypes: [],
        errorTypes: {
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '2754040237334517471': { error_kind: 'fmtstring', length: 92, item_types: [] },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.PRIVATE,
        name: 'broadcast_utility_function',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [
          {
            name: 'contract_class_id',
            type: {
              kind: 'struct',
              fields: [{ name: 'inner', type: { kind: 'field' } }],
              path: 'aztec::protocol_types::contract_class_id::ContractClassId',
            },
            visibility: 'private',
          },
          { name: 'artifact_metadata_hash', type: { kind: 'field' }, visibility: 'private' },
          { name: 'private_functions_artifact_tree_root', type: { kind: 'field' }, visibility: 'private' },
          {
            name: 'artifact_function_tree_sibling_path',
            type: { kind: 'array', length: 7, type: { kind: 'field' } },
            visibility: 'private',
          },
          { name: 'artifact_function_tree_leaf_index', type: { kind: 'field' }, visibility: 'private' },
          {
            name: 'function_data',
            type: {
              kind: 'struct',
              fields: [
                {
                  name: 'selector',
                  type: {
                    kind: 'struct',
                    fields: [{ name: 'inner', type: { kind: 'integer', sign: 'unsigned', width: 32 } }],
                    path: 'aztec::protocol_types::abis::function_selector::FunctionSelector',
                  },
                },
                { name: 'metadata_hash', type: { kind: 'field' } },
              ],
              path: 'events::utility_function_broadcasted::InnerUtilityFunction',
            },
            visibility: 'private',
          },
        ],
        returnTypes: [],
        errorTypes: {
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '2754040237334517471': { error_kind: 'fmtstring', length: 92, item_types: [] },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.PRIVATE,
        name: 'publish',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [
          { name: 'artifact_hash', type: { kind: 'field' }, visibility: 'private' },
          { name: 'private_functions_root', type: { kind: 'field' }, visibility: 'private' },
          { name: 'public_bytecode_commitment', type: { kind: 'field' }, visibility: 'private' },
        ],
        returnTypes: [],
        errorTypes: {
          '361444214588792908': { error_kind: 'string', string: 'attempt to multiply with overflow' },
          '922421554006670918': { error_kind: 'string', string: 'num_items is greater than MAX_ITEMS' },
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '2754040237334517471': { error_kind: 'fmtstring', length: 92, item_types: [] },
          '10965409165809799877': {
            error_kind: 'string',
            string: 'Given in_len to absorb is larger than the input array len',
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15669273164684982983': { error_kind: 'string', string: 'num_permutations is greater than MAX_PERMUTATIONS' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
          '16450579948625159707': { error_kind: 'string', string: 'Sponge must be in cache_size=1' },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.UTILITY,
        name: 'process_message',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [
          {
            name: 'message_ciphertext',
            type: {
              kind: 'struct',
              fields: [
                { name: 'storage', type: { kind: 'array', length: 17, type: { kind: 'field' } } },
                { name: 'len', type: { kind: 'integer', sign: 'unsigned', width: 32 } },
              ],
              path: 'std::collections::bounded_vec::BoundedVec',
            },
            visibility: 'private',
          },
          {
            name: 'message_context',
            type: {
              kind: 'struct',
              fields: [
                { name: 'tx_hash', type: { kind: 'field' } },
                {
                  name: 'unique_note_hashes_in_tx',
                  type: {
                    kind: 'struct',
                    fields: [
                      { name: 'storage', type: { kind: 'array', length: 64, type: { kind: 'field' } } },
                      { name: 'len', type: { kind: 'integer', sign: 'unsigned', width: 32 } },
                    ],
                    path: 'std::collections::bounded_vec::BoundedVec',
                  },
                },
                { name: 'first_nullifier_in_tx', type: { kind: 'field' } },
                {
                  name: 'recipient',
                  type: {
                    kind: 'struct',
                    fields: [{ name: 'inner', type: { kind: 'field' } }],
                    path: 'aztec::protocol_types::address::aztec_address::AztecAddress',
                  },
                },
              ],
              path: 'aztec::messages::processing::message_context::MessageContext',
            },
            visibility: 'private',
          },
        ],
        returnTypes: [],
        errorTypes: {
          '361444214588792908': { error_kind: 'string', string: 'attempt to multiply with overflow' },
          '992401946138144806': { error_kind: 'string', string: 'Attempted to read past end of BoundedVec' },
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '2967937905572420042': {
            error_kind: 'fmtstring',
            length: 61,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3330370348214585450': {
            error_kind: 'fmtstring',
            length: 48,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3670003311596808700': {
            error_kind: 'fmtstring',
            length: 77,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '4261968856572588300': { error_kind: 'string', string: 'Value does not fit in field' },
          '4440399188109668273': { error_kind: 'string', string: 'Input length must be a multiple of 32' },
          '9791669845391776238': {
            error_kind: 'string',
            string: '0 has a square root; you cannot claim it is not square',
          },
          '9885968605480832328': {
            error_kind: 'string',
            string: 'Attempted to read past the length of a CapsuleArray',
          },
          '10135509984888824963': { error_kind: 'fmtstring', length: 58, item_types: [{ kind: 'field' }] },
          '10791800398362570014': { error_kind: 'string', string: 'extend_from_bounded_vec out of bounds' },
          '11021520179822076911': {
            error_kind: 'string',
            string: 'Attempted to delete past the length of a CapsuleArray',
          },
          '11692359521570349358': { error_kind: 'fmtstring', length: 40, item_types: [] },
          '12327971061804302172': { error_kind: 'fmtstring', length: 98, item_types: [] },
          '12469291177396340830': { error_kind: 'string', string: 'call to assert_max_bit_size' },
          '12913276134398371456': { error_kind: 'string', string: 'push out of bounds' },
          '13557316507370296400': {
            error_kind: 'fmtstring',
            length: 130,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14938672389828944159': {
            error_kind: 'fmtstring',
            length: 146,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
          '17531474008201752295': {
            error_kind: 'fmtstring',
            length: 133,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.UTILITY,
        name: 'sync_private_state',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [],
        returnTypes: [],
        errorTypes: {
          '361444214588792908': { error_kind: 'string', string: 'attempt to multiply with overflow' },
          '992401946138144806': { error_kind: 'string', string: 'Attempted to read past end of BoundedVec' },
          '1998584279744703196': { error_kind: 'string', string: 'attempt to subtract with overflow' },
          '2967937905572420042': {
            error_kind: 'fmtstring',
            length: 61,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3330370348214585450': {
            error_kind: 'fmtstring',
            length: 48,
            item_types: [{ kind: 'field' }, { kind: 'field' }],
          },
          '3670003311596808700': {
            error_kind: 'fmtstring',
            length: 77,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '4261968856572588300': { error_kind: 'string', string: 'Value does not fit in field' },
          '4440399188109668273': { error_kind: 'string', string: 'Input length must be a multiple of 32' },
          '9791669845391776238': {
            error_kind: 'string',
            string: '0 has a square root; you cannot claim it is not square',
          },
          '9885968605480832328': {
            error_kind: 'string',
            string: 'Attempted to read past the length of a CapsuleArray',
          },
          '10135509984888824963': { error_kind: 'fmtstring', length: 58, item_types: [{ kind: 'field' }] },
          '10791800398362570014': { error_kind: 'string', string: 'extend_from_bounded_vec out of bounds' },
          '11021520179822076911': {
            error_kind: 'string',
            string: 'Attempted to delete past the length of a CapsuleArray',
          },
          '11692359521570349358': { error_kind: 'fmtstring', length: 40, item_types: [] },
          '12327971061804302172': { error_kind: 'fmtstring', length: 98, item_types: [] },
          '12469291177396340830': { error_kind: 'string', string: 'call to assert_max_bit_size' },
          '12913276134398371456': { error_kind: 'string', string: 'push out of bounds' },
          '13557316507370296400': {
            error_kind: 'fmtstring',
            length: 130,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14938672389828944159': {
            error_kind: 'fmtstring',
            length: 146,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
          '14990209321349310352': { error_kind: 'string', string: 'attempt to add with overflow' },
          '15764276373176857197': { error_kind: 'string', string: 'Stack too deep' },
          '16431471497789672479': { error_kind: 'string', string: 'Index out of bounds' },
          '17531474008201752295': {
            error_kind: 'fmtstring',
            length: 133,
            item_types: [{ kind: 'integer', sign: 'unsigned', width: 32 }],
          },
        },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
    {
      ...{
        functionType: FunctionType.PUBLIC,
        name: 'public_dispatch',
        isOnlySelf: false,
        isStatic: false,
        isInitializer: false,
        parameters: [{ name: 'selector', type: { kind: 'field' }, visibility: 'private' }],
        returnTypes: [],
        errorTypes: { '1335198680857977525': { error_kind: 'string', string: 'No public functions' } },
      },
      bytecode: Buffer.from([]),
      debugSymbols: '',
    },
  ],
  nonDispatchPublicFunctions: [],
  outputs: { structs: {}, globals: {} },
  storageLayout: {},
  fileMap: {},
};

export class ContractClassRegistryContract extends ContractBase {
  private constructor(wallet: Wallet) {
    super(ProtocolContractAddress.ContractClassRegistry, ContractClassRegistryContractArtifact, wallet);
  }

  public static at(wallet: Wallet): ContractClassRegistryContract {
    return new ContractClassRegistryContract(wallet);
  }

  declare public methods: {
    /** broadcast_private_function(contract_class_id: struct, artifact_metadata_hash: field, utility_functions_artifact_tree_root: field, private_function_tree_sibling_path: array, private_function_tree_leaf_index: field, artifact_function_tree_sibling_path: array, artifact_function_tree_leaf_index: field, function_data: struct) */
    broadcast_private_function: ((
      contract_class_id: WrappedFieldLike,
      artifact_metadata_hash: FieldLike,
      utility_functions_artifact_tree_root: FieldLike,
      private_function_tree_sibling_path: FieldLike[],
      private_function_tree_leaf_index: FieldLike,
      artifact_function_tree_sibling_path: FieldLike[],
      artifact_function_tree_leaf_index: FieldLike,
      function_data: any,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** broadcast_utility_function(contract_class_id: struct, artifact_metadata_hash: field, private_functions_artifact_tree_root: field, artifact_function_tree_sibling_path: array, artifact_function_tree_leaf_index: field, function_data: struct) */
    broadcast_utility_function: ((
      contract_class_id: WrappedFieldLike,
      artifact_metadata_hash: FieldLike,
      private_functions_artifact_tree_root: FieldLike,
      artifact_function_tree_sibling_path: FieldLike[],
      artifact_function_tree_leaf_index: FieldLike,
      function_data: any,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: any) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** publish(artifact_hash: field, private_functions_root: field, public_bytecode_commitment: field) */
    publish: ((
      artifact_hash: FieldLike,
      private_functions_root: FieldLike,
      public_bytecode_commitment: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
